spin_version = "1"
authors = ["Eric <egregory04@gmail.com>"]
description = "Go Wasm HTTP handler"
name = "gogo-wasm"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "gogo-wasm"
source = "main.wasm"
environment = { VERSION = "v0.1.0" }
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go"

